  
name: Tests
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci/cat_recognition:latest --tag islasgeci/cat_recognition:${GITHUB_SHA:0:4} .
    - name: Verifica el formato
      run: docker run islasgeci/cat_recognition:latest make check
    - name: Corre pruebas y evalúa cobertura
      run: docker run islasgeci/cat_recognition:latest make coverage
    - name: Evalúa resistencia a mutaciones
      run: docker run islasgeci/cat_recognition:latest make mutants
    - name: Docker log-in
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - name: Sube latest a Docker Hub
      run: docker push islasgeci/cat_recognition:latest
    - name: Sube sha a Docker Hub
      run: docker push islasgeci/cat_recognition:${GITHUB_SHA:0:4}
